user_panel:
    resource: "@UserPanelBundle/Controller/"
    type:     annotation
    prefix:   /
    
admin_panel:
    resource: "@AdminPanelBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
